[[redirects]]
  from = "/stack-navigator/mpa-with-navigation-api/*"
  to = "/stack-navigator/navigation-api/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Access-Control-Allow-Origin = "*"
